### PR TITLE
Fixing installation + bashrc backup + option to uninstall flirt

### PR DESCRIPTION
**Pull request by TheGhostboi64**

### CODE REVIEW

**Review by xezo360hye — CHANGES_REQUESTED** [review]
Location of the bashrc file should not be hardcoded as /root/.bashrc but as "$HOME/.bashrc". Also bashrc backup file should also be dotted I think

**Comment by TheGhostboi64** [comment]
> Location of the bashrc file should not be hardcoded as /root/.bashrc but as "$HOME/.bashrc". Also bashrc backup file should also be dotted I think

alright I will do that

**Comment by TheGhostboi64** [comment]
It should Work now

**Comment by TheGhostboi64** [comment]
Still there?

**Comment by TheGhostboi64** [comment]
hello?

**Comment by xezo360hye** [comment]
I don't even know what to say here. Sorry

**Comment by TheGhostboi64** [comment]
> I don't even know what to say here. Sorry

No worries! It's fine.

**Pull request merged**
